dist: xenial
sudo: false
language: python
python:
- '2.7'
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  password:
    secure: Q9siahqg5eheOV2M29FOWIdaSIRIlvhI+6FqTTMpgz6qjzrkoK2MCfFuaPh0rkdTUYYpP0Yxcj2zo9Xqu50VIq57zxQaLBprQsLch6QAi1ktvRfnhzuvNnQQDR7QAqdR1xHO+TPgKZZYzROKhDc5tngJdSamVZom+y/Vpss7QUEpF33AWe/y5f+cVMKvKz0hauGt+cA3r5nXQfn5HELvlAlZ8EycI9ik8/+rbnqzgAli9g1F5gz6MV8v8Q4VklRcvgYy6wyN6PQcUYnsEU9FQYRJCK8no7/dKQw526ZNgKf03LO5+tHULxZ4IfS6DaFOKzUfoKhSnSWyIaViod0j2ik8z8c6E8cfn6O9WLfnyrS+GjcTrkpwgpf4eYm5WwKhKTLJLXz+PXOwobW9/rDUumk7pAF1eXsybbt7IGo3sEGPYly1TBLoDocBnMm45usdWKMiJfJ0zgwFZsl9RBXvfVJ2UW7YCrsb9fRiAMb4SYwyhEO1nIcrowzZT64kp1cZXvYEhmQOOYrpU38aRg2cskYIWKut16yvlQYQ7rJ73LU7MS0sKEtI5lrRcOGLmWLXqJS84WeJoQTKEDj+o+bCkD3CmzahWz0CNOym2WOCyYrnUzRywEJqGwGTWl/f57bRHkvpVBVmbIlqA5Gg7zqeNKt8my3mU9J8yRlFgJOueLA=
